/* Skill-specific detailed content */
const SKILL_DETAILS = {
  html: {
    overview: 'HTML (HyperText Markup Language) is the foundation of every website. It defines the structure and meaning of web content using elements like headings, paragraphs, links, images, and forms.',
    importance: 'Every web developer starts with HTML. It powers accessibility, SEO, and is required before learning CSS or JavaScript. Companies expect solid HTML knowledge for frontend and full-stack roles.',
    roadmap: [
      { title: 'HTML Basics', desc: 'Tags, elements, attributes, and document structure' },
      { title: 'Semantic HTML', desc: 'header, nav, main, article, section, footer' },
      { title: 'Forms & Media', desc: 'Inputs, validation, images, audio, and video' },
      { title: 'Accessibility & SEO', desc: 'ARIA labels, alt text, meta tags, and best practices' },
    ],
    keyTopics: ['Document structure', 'Semantic elements', 'Links & navigation', 'Lists & tables', 'Forms & inputs', 'Multimedia embedding', 'HTML5 APIs', 'Accessibility (a11y)'],
    projects: [
      { title: 'Personal Portfolio Page', desc: 'Build a single-page portfolio using semantic HTML only.' },
      { title: 'Recipe Blog', desc: 'Create structured recipe pages with headings, lists, and images.' },
      { title: 'Survey Form', desc: 'Design an accessible multi-section registration form.' },
    ],
    careers: ['Frontend Developer', 'UI Developer', 'Web Designer', 'Full-Stack Developer', 'WordPress Developer'],
    interviewQuestions: [
      'What is the difference between block and inline elements?',
      'Explain semantic HTML and why it matters.',
      'What are data attributes used for?',
      'How do you improve accessibility in HTML?',
      'What is the purpose of the DOCTYPE declaration?',
    ],
    resources: [
      { title: 'MDN HTML Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', type: 'Docs' },
      { title: 'freeCodeCamp Responsive Web Design', url: 'https://www.freecodecamp.org', type: 'Course' },
      { title: 'HTML5 Doctor', url: 'http://html5doctor.com', type: 'Reference' },
    ],
    levels: {
      beginner: { topics: ['Basic tags', 'Headings & paragraphs', 'Links & images', 'Lists'] },
      intermediate: { topics: ['Semantic layout', 'Forms & validation', 'Tables', 'Meta & SEO tags'] },
      advanced: { topics: ['Web Components', 'Microdata & Schema', 'Performance optimization', 'Cross-browser compatibility'] },
    },
  },
  css: {
    overview: 'CSS (Cascading Style Sheets) controls the visual presentation of web pages — colors, layouts, typography, animations, and responsive design across all screen sizes.',
    importance: 'Great CSS separates amateur sites from professional ones. It is essential for UI/UX roles and pairs with HTML and JavaScript in every modern web stack.',
    roadmap: [
      { title: 'Selectors & Properties', desc: 'Colors, fonts, spacing, and the box model' },
      { title: 'Flexbox & Grid', desc: 'Modern layout systems for responsive design' },
      { title: 'Responsive Design', desc: 'Media queries, mobile-first, and fluid layouts' },
      { title: 'Animations & Preprocessors', desc: 'Transitions, keyframes, Sass, and CSS variables' },
    ],
    keyTopics: ['Box model', 'Flexbox', 'CSS Grid', 'Responsive design', 'Typography', 'Animations', 'CSS variables', 'Preprocessors (Sass)'],
    projects: [
      { title: 'Landing Page Clone', desc: 'Recreate a popular landing page with pixel-perfect CSS.' },
      { title: 'CSS Grid Dashboard', desc: 'Build a responsive admin dashboard layout.' },
      { title: 'Animated UI Components', desc: 'Create buttons, cards, and modals with smooth transitions.' },
    ],
    careers: ['UI Developer', 'Frontend Developer', 'Web Designer', 'CSS Specialist', 'Design Systems Engineer'],
    interviewQuestions: [
      'Explain the CSS box model.',
      'What is the difference between Flexbox and Grid?',
      'How does specificity work in CSS?',
      'What is a CSS reset vs normalize?',
      'How do you center an element horizontally and vertically?',
    ],
    resources: [
      { title: 'MDN CSS Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS', type: 'Docs' },
      { title: 'CSS-Tricks', url: 'https://css-tricks.com', type: 'Blog' },
      { title: 'Flexbox Froggy', url: 'https://flexboxfroggy.com', type: 'Practice' },
    ],
    levels: {
      beginner: { topics: ['Selectors', 'Colors & fonts', 'Margin & padding', 'Basic layouts'] },
      intermediate: { topics: ['Flexbox & Grid', 'Media queries', 'Positioning', 'Pseudo-classes'] },
      advanced: { topics: ['CSS animations', 'Custom properties', 'Architecture (BEM)', 'Performance & critical CSS'] },
    },
  },
  javascript: {
    overview: 'JavaScript is the programming language of the web. It adds interactivity, handles user events, communicates with APIs, and powers both frontend frameworks and backend runtimes like Node.js.',
    importance: 'JavaScript is the most widely used programming language. It unlocks full-stack development, mobile apps (React Native), and is required for nearly every modern web job.',
    roadmap: [
      { title: 'JS Fundamentals', desc: 'Variables, functions, loops, arrays, and objects' },
      { title: 'DOM Manipulation', desc: 'Events, selectors, and dynamic UI updates' },
      { title: 'Async JavaScript', desc: 'Promises, async/await, fetch API, and REST' },
      { title: 'Frameworks & Tools', desc: 'React or Vue, npm, bundlers, and testing' },
    ],
    keyTopics: ['Variables & types', 'Functions & scope', 'DOM APIs', 'Async programming', 'ES6+ features', 'AJAX & Fetch', 'Error handling', 'Modules'],
    projects: [
      { title: 'Todo App', desc: 'CRUD app with localStorage and DOM manipulation.' },
      { title: 'Weather Dashboard', desc: 'Fetch live data from a public weather API.' },
      { title: 'Quiz Application', desc: 'Interactive quiz with scoring and timer logic.' },
    ],
    careers: ['JavaScript Developer', 'Frontend Developer', 'Full-Stack Developer', 'Node.js Developer', 'React Developer'],
    interviewQuestions: [
      'What is the difference between let, const, and var?',
      'Explain closures with an example.',
      'What is the event loop?',
      'How does prototypal inheritance work?',
      'What is the difference between == and ===?',
    ],
    resources: [
      { title: 'JavaScript.info', url: 'https://javascript.info', type: 'Course' },
      { title: 'MDN JavaScript Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', type: 'Docs' },
      { title: 'Eloquent JavaScript', url: 'https://eloquentjavascript.net', type: 'Book' },
    ],
    levels: {
      beginner: { topics: ['Syntax & variables', 'Conditionals & loops', 'Functions', 'Arrays & objects'] },
      intermediate: { topics: ['DOM manipulation', 'Events', 'Promises & fetch', 'ES6 modules'] },
      advanced: { topics: ['Design patterns', 'Performance tuning', 'Testing (Jest)', 'Framework internals'] },
    },
  },
  python: {
    overview: 'Python is a versatile, readable programming language used in web development, data science, automation, AI, scripting, and backend services worldwide.',
    importance: 'Python tops job demand in data science and AI. Its simple syntax makes it ideal for beginners while powering enterprise systems at Google, Netflix, and NASA.',
    roadmap: [
      { title: 'Python Basics', desc: 'Syntax, data types, control flow, and functions' },
      { title: 'OOP & Modules', desc: 'Classes, inheritance, packages, and pip' },
      { title: 'Libraries & Frameworks', desc: 'NumPy, Pandas, Flask, or Django' },
      { title: 'Specialization', desc: 'Data science, web dev, or automation track' },
    ],
    keyTopics: ['Variables & data types', 'Functions & modules', 'OOP', 'File I/O', 'Exception handling', 'List comprehensions', 'Virtual environments', 'Decorators'],
    projects: [
      { title: 'CLI Task Manager', desc: 'Command-line app to manage daily tasks with file storage.' },
      { title: 'Web Scraper', desc: 'Extract and analyze data from websites using BeautifulSoup.' },
      { title: 'Flask Blog API', desc: 'REST API with user authentication and database integration.' },
    ],
    careers: ['Python Developer', 'Data Scientist', 'Backend Developer', 'Automation Engineer', 'ML Engineer'],
    interviewQuestions: [
      'What are Python decorators?',
      'Explain list vs tuple vs set.',
      'What is the GIL in Python?',
      'How does memory management work in Python?',
      'What is the difference between deep copy and shallow copy?',
    ],
    resources: [
      { title: 'Python.org Tutorial', url: 'https://docs.python.org/3/tutorial/', type: 'Docs' },
      { title: 'Real Python', url: 'https://realpython.com', type: 'Course' },
      { title: 'Automate the Boring Stuff', url: 'https://automatetheboringstuff.com', type: 'Book' },
    ],
    levels: {
      beginner: { topics: ['Syntax', 'Data structures', 'Loops & functions', 'Basic I/O'] },
      intermediate: { topics: ['OOP', 'Modules & pip', 'Error handling', 'File & JSON handling'] },
      advanced: { topics: ['Decorators & generators', 'Multithreading', 'Design patterns', 'Performance profiling'] },
    },
  },
  java: {
    overview: 'Java is a robust, object-oriented language used for enterprise applications, Android development, backend microservices, and large-scale distributed systems.',
    importance: 'Java powers banks, e-commerce giants, and Android apps. It offers strong typing, vast libraries, and remains a top language for enterprise and backend careers.',
    roadmap: [
      { title: 'Core Java', desc: 'Syntax, OOP, collections, and exception handling' },
      { title: 'Advanced Java', desc: 'Multithreading, streams, generics, and JDBC' },
      { title: 'Frameworks', desc: 'Spring Boot, REST APIs, and Maven/Gradle' },
      { title: 'Enterprise Patterns', desc: 'Microservices, JPA, and cloud deployment' },
    ],
    keyTopics: ['OOP principles', 'Collections framework', 'Exception handling', 'Multithreading', 'JVM basics', 'Spring Boot', 'JDBC & JPA', 'Design patterns'],
    projects: [
      { title: 'Library Management System', desc: 'Console or GUI app with OOP and file/database storage.' },
      { title: 'REST API with Spring Boot', desc: 'CRUD API with authentication and MySQL integration.' },
      { title: 'Android Notes App', desc: 'Mobile app storing notes with RecyclerView and SQLite.' },
    ],
    careers: ['Java Developer', 'Backend Engineer', 'Android Developer', 'Software Engineer', 'Enterprise Architect'],
    interviewQuestions: [
      'What is the difference between JDK, JRE, and JVM?',
      'Explain inheritance vs composition.',
      'What are Java interfaces used for?',
      'How does garbage collection work?',
      'What is the difference between HashMap and Hashtable?',
    ],
    resources: [
      { title: 'Oracle Java Tutorials', url: 'https://docs.oracle.com/javase/tutorial/', type: 'Docs' },
      { title: 'Spring Guides', url: 'https://spring.io/guides', type: 'Course' },
      { title: 'Baeldung', url: 'https://www.baeldung.com', type: 'Blog' },
    ],
    levels: {
      beginner: { topics: ['Syntax & OOP', 'Variables & methods', 'Control flow', 'Arrays & strings'] },
      intermediate: { topics: ['Collections', 'Exception handling', 'File I/O', 'Basic multithreading'] },
      advanced: { topics: ['Spring ecosystem', 'JVM tuning', 'Concurrency utilities', 'Microservices'] },
    },
  },
  c: {
    overview: 'C is a low-level systems programming language that forms the foundation of operating systems, embedded devices, compilers, and performance-critical software.',
    importance: 'Learning C teaches how computers work at a fundamental level. It is essential for systems programming, embedded engineering, cybersecurity, and understanding other languages.',
    roadmap: [
      { title: 'C Fundamentals', desc: 'Variables, pointers, arrays, and control structures' },
      { title: 'Memory Management', desc: 'malloc, free, stack vs heap, and pointer arithmetic' },
      { title: 'Data Structures', desc: 'Linked lists, stacks, queues implemented in C' },
      { title: 'Systems Programming', desc: 'File I/O, sockets, and OS-level concepts' },
    ],
    keyTopics: ['Pointers & memory', 'Arrays & strings', 'Structs & unions', 'Dynamic memory', 'Preprocessor', 'File I/O', 'Function pointers', 'Bit manipulation'],
    projects: [
      { title: 'Command-Line Calculator', desc: 'Parse expressions and perform arithmetic operations.' },
      { title: 'Custom Shell', desc: 'Build a basic shell that executes system commands.' },
      { title: 'Data Structures Library', desc: 'Implement linked list, stack, and queue from scratch.' },
    ],
    careers: ['Systems Programmer', 'Embedded Engineer', 'Firmware Developer', 'OS Developer', 'Cybersecurity Analyst'],
    interviewQuestions: [
      'What is a pointer and why is it used?',
      'Explain stack vs heap memory.',
      'What causes a segmentation fault?',
      'What is the difference between malloc and calloc?',
      'How do you prevent memory leaks?',
    ],
    resources: [
      { title: 'CS50 C Lectures', url: 'https://cs50.harvard.edu', type: 'Course' },
      { title: 'Learn C the Hard Way', url: 'https://learncodethehardway.org/c/', type: 'Book' },
      { title: 'C Programming Language (K&R)', url: 'https://en.wikipedia.org/wiki/The_C_Programming_Language', type: 'Book' },
    ],
    levels: {
      beginner: { topics: ['Syntax & types', 'Control flow', 'Functions', 'Basic pointers'] },
      intermediate: { topics: ['Dynamic memory', 'Structs', 'File handling', 'Modular programming'] },
      advanced: { topics: ['Systems calls', 'Networking in C', 'Optimization', 'Embedded programming'] },
    },
  },
  cpp: {
    overview: 'C++ extends C with object-oriented and generic programming features. It powers game engines, browsers, high-frequency trading systems, and performance-critical applications.',
    importance: 'C++ is prized for speed and control. It is the language of choice for game development (Unreal), finance, robotics, and anywhere performance is critical.',
    roadmap: [
      { title: 'C++ Basics', desc: 'Syntax, OOP, references, and STL containers' },
      { title: 'Modern C++', desc: 'C++11/14/17 features, smart pointers, and lambdas' },
      { title: 'Advanced Topics', desc: 'Templates, move semantics, and multithreading' },
      { title: 'Specialization', desc: 'Game dev, competitive programming, or systems' },
    ],
    keyTopics: ['OOP in C++', 'STL containers', 'Pointers & references', 'Templates', 'Smart pointers', 'RAII', 'Multithreading', 'Move semantics'],
    projects: [
      { title: '2D Game Engine', desc: 'Build a simple game loop with SDL or SFML.' },
      { title: 'Custom Vector Class', desc: 'Implement a dynamic array with templates.' },
      { title: 'File Compression Tool', desc: 'Compress and decompress text files with Huffman coding.' },
    ],
    careers: ['C++ Developer', 'Game Developer', 'Quantitative Developer', 'Systems Engineer', 'Robotics Engineer'],
    interviewQuestions: [
      'What is RAII in C++?',
      'Explain the difference between stack and heap allocation.',
      'What are smart pointers?',
      'What is the Rule of Three/Five?',
      'How do virtual functions work?',
    ],
    resources: [
      { title: 'LearnCpp.com', url: 'https://www.learncpp.com', type: 'Course' },
      { title: 'cppreference.com', url: 'https://en.cppreference.com', type: 'Docs' },
      { title: 'LeetCode C++', url: 'https://leetcode.com', type: 'Practice' },
    ],
    levels: {
      beginner: { topics: ['Syntax & OOP', 'Variables & functions', 'Basic STL', 'References'] },
      intermediate: { topics: ['Templates', 'Smart pointers', 'Exception handling', 'File streams'] },
      advanced: { topics: ['Move semantics', 'Concurrency', 'Metaprogramming', 'Performance optimization'] },
    },
  },
  sql: {
    overview: 'SQL (Structured Query Language) is the standard language for managing and querying relational databases. It is used to store, retrieve, and analyze structured data.',
    importance: 'Every application needs a database. SQL skills are required for backend developers, data analysts, data scientists, and DBAs across all industries.',
    roadmap: [
      { title: 'SQL Basics', desc: 'SELECT, INSERT, UPDATE, DELETE, and filtering' },
      { title: 'Joins & Aggregations', desc: 'INNER/OUTER joins, GROUP BY, and HAVING' },
      { title: 'Advanced Queries', desc: 'Subqueries, CTEs, window functions, and indexes' },
      { title: 'Database Design', desc: 'Normalization, ER diagrams, and optimization' },
    ],
    keyTopics: ['SELECT queries', 'JOINs', 'Aggregations', 'Subqueries & CTEs', 'Indexes', 'Normalization', 'Transactions', 'Window functions'],
    projects: [
      { title: 'E-Commerce Database', desc: 'Design schema for products, orders, and customers.' },
      { title: 'Analytics Dashboard Queries', desc: 'Write complex reports with window functions.' },
      { title: 'Database Migration Script', desc: 'Create and populate a production-ready schema.' },
    ],
    careers: ['Database Administrator', 'Data Analyst', 'Backend Developer', 'Data Engineer', 'BI Developer'],
    interviewQuestions: [
      'What is the difference between INNER and LEFT JOIN?',
      'Explain database normalization.',
      'What is an index and when should you use one?',
      'What are ACID properties?',
      'How do window functions differ from GROUP BY?',
    ],
    resources: [
      { title: 'SQLBolt', url: 'https://sqlbolt.com', type: 'Course' },
      { title: 'Mode SQL Tutorial', url: 'https://mode.com/sql-tutorial/', type: 'Course' },
      { title: 'LeetCode Database', url: 'https://leetcode.com/problemset/database/', type: 'Practice' },
    ],
    levels: {
      beginner: { topics: ['SELECT & WHERE', 'INSERT/UPDATE/DELETE', 'Basic joins', 'ORDER BY & LIMIT'] },
      intermediate: { topics: ['Complex joins', 'Aggregations', 'Subqueries', 'Indexes basics'] },
      advanced: { topics: ['Window functions', 'Query optimization', 'Stored procedures', 'Database design'] },
    },
  },
  ai: {
    overview: 'Artificial Intelligence focuses on building systems that can learn, reason, and make decisions. It spans machine learning, deep learning, NLP, computer vision, and generative AI.',
    importance: 'AI is transforming every industry. Demand for AI engineers is exploding as companies adopt chatbots, recommendation systems, and automation at scale.',
    roadmap: [
      { title: 'Math Foundations', desc: 'Linear algebra, calculus, probability, and statistics' },
      { title: 'Machine Learning', desc: 'Supervised/unsupervised learning with scikit-learn' },
      { title: 'Deep Learning', desc: 'Neural networks, TensorFlow/PyTorch, and CNNs/RNNs' },
      { title: 'Applied AI', desc: 'NLP, computer vision, LLMs, and deployment' },
    ],
    keyTopics: ['Machine learning', 'Neural networks', 'Deep learning', 'NLP', 'Computer vision', 'Model evaluation', 'Feature engineering', 'MLOps'],
    projects: [
      { title: 'Image Classifier', desc: 'Train a CNN to classify images using TensorFlow or PyTorch.' },
      { title: 'Sentiment Analysis Bot', desc: 'Analyze text sentiment using NLP techniques.' },
      { title: 'Recommendation Engine', desc: 'Build a collaborative filtering system for products.' },
    ],
    careers: ['AI Engineer', 'ML Engineer', 'Data Scientist', 'NLP Engineer', 'Computer Vision Engineer'],
    interviewQuestions: [
      'What is the difference between AI, ML, and deep learning?',
      'Explain overfitting and how to prevent it.',
      'What is gradient descent?',
      'How do convolutional neural networks work?',
      'What evaluation metrics do you use for classification?',
    ],
    resources: [
      { title: 'fast.ai', url: 'https://www.fast.ai', type: 'Course' },
      { title: 'Google ML Crash Course', url: 'https://developers.google.com/machine-learning/crash-course', type: 'Course' },
      { title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', type: 'Practice' },
    ],
    levels: {
      beginner: { topics: ['AI concepts', 'Python for ML', 'Basic statistics', 'scikit-learn intro'] },
      intermediate: { topics: ['Model tuning', 'Feature engineering', 'Neural network basics', 'Evaluation metrics'] },
      advanced: { topics: ['Deep learning', 'Transformers & LLMs', 'MLOps', 'Production deployment'] },
    },
  },
  'data-science': {
    overview: 'Data Science combines statistics, programming, and domain knowledge to extract insights and build predictive models from complex datasets.',
    importance: 'Data scientists drive business decisions at top companies. The field offers high salaries and growing demand across healthcare, finance, tech, and retail.',
    roadmap: [
      { title: 'Statistics & Python', desc: 'Probability, hypothesis testing, NumPy, and Pandas' },
      { title: 'Data Wrangling', desc: 'Cleaning, transforming, and exploring datasets' },
      { title: 'Machine Learning', desc: 'Regression, classification, clustering, and model selection' },
      { title: 'Communication', desc: 'Visualization, storytelling, and deploying models' },
    ],
    keyTopics: ['Statistics', 'Data cleaning', 'Exploratory analysis', 'Machine learning', 'Data visualization', 'Feature engineering', 'Model evaluation', 'A/B testing'],
    projects: [
      { title: 'Customer Churn Prediction', desc: 'Predict which customers will leave using classification models.' },
      { title: 'Sales Forecasting', desc: 'Time-series analysis to predict future revenue.' },
      { title: 'Data Storytelling Dashboard', desc: 'Interactive visualizations with Plotly or Tableau.' },
    ],
    careers: ['Data Scientist', 'ML Engineer', 'Research Analyst', 'Quantitative Analyst', 'AI Specialist'],
    interviewQuestions: [
      'Explain bias-variance tradeoff.',
      'What is the difference between correlation and causation?',
      'How do you handle missing data?',
      'Describe a machine learning project you worked on.',
      'What is cross-validation and why use it?',
    ],
    resources: [
      { title: 'Kaggle', url: 'https://www.kaggle.com', type: 'Practice' },
      { title: 'DataCamp', url: 'https://www.datacamp.com', type: 'Course' },
      { title: 'StatQuest YouTube', url: 'https://www.youtube.com/user/joshstarmer', type: 'Video' },
    ],
    levels: {
      beginner: { topics: ['Python & Pandas', 'Basic statistics', 'Data visualization', 'Data cleaning'] },
      intermediate: { topics: ['Machine learning', 'Feature engineering', 'Model evaluation', 'SQL for data'] },
      advanced: { topics: ['Deep learning', 'Big data tools', 'Experiment design', 'Production ML pipelines'] },
    },
  },
  'data-analytics': {
    overview: 'Data Analytics focuses on examining datasets to find trends, create reports, and support business decisions using SQL, spreadsheets, and visualization tools.',
    importance: 'Every company needs analysts to turn raw data into actionable insights. It is one of the most accessible and in-demand tech careers for students.',
    roadmap: [
      { title: 'Excel & Spreadsheets', desc: 'Formulas, pivot tables, and data cleaning' },
      { title: 'SQL Fundamentals', desc: 'Querying databases and building reports' },
      { title: 'Visualization', desc: 'Tableau, Power BI, or Python charts' },
      { title: 'Business Analytics', desc: 'KPIs, dashboards, and stakeholder presentations' },
    ],
    keyTopics: ['SQL queries', 'Excel & spreadsheets', 'Data visualization', 'KPI tracking', 'A/B testing', 'Dashboard design', 'Report writing', 'Statistical summaries'],
    projects: [
      { title: 'Sales Performance Dashboard', desc: 'Track revenue, growth, and regional performance in Tableau.' },
      { title: 'Marketing Campaign Analysis', desc: 'Measure ROI and conversion rates from campaign data.' },
      { title: 'Customer Segmentation Report', desc: 'Group customers by behavior using SQL and visualization.' },
    ],
    careers: ['Data Analyst', 'Business Analyst', 'BI Developer', 'Marketing Analyst', 'Operations Analyst'],
    interviewQuestions: [
      'How do you approach a new dataset?',
      'What is the difference between mean and median?',
      'Write a SQL query to find top customers by revenue.',
      'How do you present findings to non-technical stakeholders?',
      'What tools do you use for data visualization?',
    ],
    resources: [
      { title: 'Google Data Analytics Certificate', url: 'https://www.coursera.org/professional-certificates/google-data-analytics', type: 'Course' },
      { title: 'SQLBolt', url: 'https://sqlbolt.com', type: 'Course' },
      { title: 'Tableau Public', url: 'https://public.tableau.com', type: 'Tool' },
    ],
    levels: {
      beginner: { topics: ['Excel basics', 'Simple SQL', 'Basic charts', 'Data types'] },
      intermediate: { topics: ['Complex SQL', 'Pivot tables', 'Dashboard tools', 'Statistical summaries'] },
      advanced: { topics: ['Predictive analytics', 'Python/R for analysis', 'ETL basics', 'Executive reporting'] },
    },
  },
  'web-dev': {
    overview: 'Web Development covers building complete websites and applications — combining frontend (HTML, CSS, JS), backend (servers, APIs), databases, and deployment.',
    importance: 'Web developers are always in demand. Full-stack skills open doors to startups, agencies, and tech giants building products used by millions daily.',
    roadmap: [
      { title: 'Frontend Foundations', desc: 'HTML, CSS, JavaScript, and responsive design' },
      { title: 'Frontend Framework', desc: 'React, Vue, or Angular for component-based UIs' },
      { title: 'Backend & APIs', desc: 'Node.js, Express, REST APIs, and authentication' },
      { title: 'Deploy & Scale', desc: 'Databases, cloud hosting, CI/CD, and portfolios' },
    ],
    keyTopics: ['HTML/CSS/JS', 'Responsive design', 'React or Vue', 'REST APIs', 'Node.js', 'Databases', 'Authentication', 'Deployment'],
    projects: [
      { title: 'Full-Stack Blog', desc: 'CRUD blog with user auth, comments, and database.' },
      { title: 'E-Commerce Store', desc: 'Product catalog, cart, and checkout flow.' },
      { title: 'Real-Time Chat App', desc: 'WebSocket-based messaging with online presence.' },
    ],
    careers: ['Frontend Developer', 'Full-Stack Developer', 'Web Developer', 'UI Engineer', 'Freelance Developer'],
    interviewQuestions: [
      'Explain the request-response cycle.',
      'What is the difference between SSR and CSR?',
      'How does JWT authentication work?',
      'What are REST API best practices?',
      'How do you optimize website performance?',
    ],
    resources: [
      { title: 'freeCodeCamp', url: 'https://www.freecodecamp.org', type: 'Course' },
      { title: 'The Odin Project', url: 'https://www.theodinproject.com', type: 'Course' },
      { title: 'MDN Web Docs', url: 'https://developer.mozilla.org', type: 'Docs' },
    ],
    levels: {
      beginner: { topics: ['HTML/CSS/JS basics', 'Git fundamentals', 'Simple layouts', 'Basic DOM'] },
      intermediate: { topics: ['Framework (React)', 'API integration', 'Responsive design', 'npm & bundlers'] },
      advanced: { topics: ['Full-stack architecture', 'Auth & security', 'Testing', 'Cloud deployment'] },
    },
  },
  cybersecurity: {
    overview: 'Cybersecurity protects systems, networks, and data from cyber threats through practices like encryption, penetration testing, incident response, and security architecture.',
    importance: 'Cyber attacks cost billions annually. Skilled security professionals are critically needed across government, finance, healthcare, and every tech company.',
    roadmap: [
      { title: 'Networking Basics', desc: 'TCP/IP, DNS, firewalls, and network protocols' },
      { title: 'Security Fundamentals', desc: 'CIA triad, encryption, auth, and common threats' },
      { title: 'Offensive Security', desc: 'Pen testing, vulnerability assessment, and tools' },
      { title: 'Certifications', desc: 'CompTIA Security+, CEH, or OSCP path' },
    ],
    keyTopics: ['Network security', 'Cryptography', 'Penetration testing', 'Incident response', 'OWASP Top 10', 'Firewalls & IDS', 'Risk assessment', 'Security policies'],
    projects: [
      { title: 'Home Lab Setup', desc: 'Configure a virtual lab with Kali Linux and vulnerable VMs.' },
      { title: 'Vulnerability Assessment Report', desc: 'Scan and document vulnerabilities on a test network.' },
      { title: 'Security Policy Document', desc: 'Write an organizational security policy and incident plan.' },
    ],
    careers: ['Security Analyst', 'Penetration Tester', 'SOC Analyst', 'Security Engineer', 'CISO'],
    interviewQuestions: [
      'What is the CIA triad?',
      'Explain the difference between symmetric and asymmetric encryption.',
      'What is a SQL injection attack?',
      'How does multi-factor authentication work?',
      'What steps do you take during incident response?',
    ],
    resources: [
      { title: 'TryHackMe', url: 'https://tryhackme.com', type: 'Practice' },
      { title: 'Cybrary', url: 'https://www.cybrary.it', type: 'Course' },
      { title: 'OWASP', url: 'https://owasp.org', type: 'Reference' },
    ],
    levels: {
      beginner: { topics: ['Security concepts', 'Basic networking', 'Password security', 'Malware types'] },
      intermediate: { topics: ['Cryptography basics', 'Web vulnerabilities', 'Linux security', 'Wireshark'] },
      advanced: { topics: ['Pen testing', 'Forensics', 'Cloud security', 'Red team operations'] },
    },
  },
  cloud: {
    overview: 'Cloud Computing delivers computing services — servers, storage, databases, networking, and software — over the internet with on-demand scalability and pay-as-you-go pricing.',
    importance: 'Over 90% of enterprises use cloud services. AWS, Azure, and GCP skills are among the highest-paying and fastest-growing in all of technology.',
    roadmap: [
      { title: 'Cloud Concepts', desc: 'IaaS, PaaS, SaaS, virtualization, and cloud models' },
      { title: 'Platform Deep Dive', desc: 'AWS, Azure, or GCP core services and console' },
      { title: 'DevOps & Containers', desc: 'Docker, Kubernetes, CI/CD, and IaC (Terraform)' },
      { title: 'Architecture & Certs', desc: 'Solution design, security, and certification prep' },
    ],
    keyTopics: ['Cloud models', 'AWS/Azure/GCP', 'Virtual machines', 'Containers & Kubernetes', 'Serverless', 'CI/CD', 'IaC (Terraform)', 'Cloud security'],
    projects: [
      { title: 'Deploy a Web App', desc: 'Host a full-stack app on AWS EC2 or Azure App Service.' },
      { title: 'Serverless API', desc: 'Build an API with AWS Lambda and API Gateway.' },
      { title: 'Kubernetes Cluster', desc: 'Containerize an app and deploy to a K8s cluster.' },
    ],
    careers: ['Cloud Engineer', 'DevOps Engineer', 'Solutions Architect', 'SRE', 'Cloud Security Engineer'],
    interviewQuestions: [
      'What is the difference between IaaS, PaaS, and SaaS?',
      'Explain auto-scaling in the cloud.',
      'What is the shared responsibility model?',
      'How does Docker differ from a virtual machine?',
      'What AWS services would you use for a web application?',
    ],
    resources: [
      { title: 'AWS Skill Builder', url: 'https://skillbuilder.aws', type: 'Course' },
      { title: 'Microsoft Learn Azure', url: 'https://learn.microsoft.com/azure', type: 'Course' },
      { title: 'Google Cloud Skills Boost', url: 'https://www.cloudskillsboost.google', type: 'Course' },
    ],
    levels: {
      beginner: { topics: ['Cloud concepts', 'Console navigation', 'Basic VMs', 'Storage services'] },
      intermediate: { topics: ['Networking in cloud', 'IAM & security', 'Docker basics', 'CI/CD pipelines'] },
      advanced: { topics: ['Kubernetes', 'Terraform/IaC', 'Multi-cloud architecture', 'Cost optimization'] },
    },
  },
};

function getSkillDetail(id) {
  return SKILL_DETAILS[id] || null;
}
